

@rootApi = http://localhost:8000

@userApi = {{rootApi}}/api/v1/user

@burrowApi = {{rootApi}}/api/v1/burrow


### Server Testing 
GET {{rootApi}}


# =========== user Api 

### Get User 
GET  {{userApi}}
Content-Type: application/json



### Create data in database
POST {{userApi}}
Content-Type: application/json

{
    "role": "admin",
    "fName": "Sagar",
    "lName": "Pyakurel",
    "phone" : "045235",
    "address" : "Sydney",
    "email" : "pwsedaasada@email",
    "password": "123456"
}



# ============= Book Api 

# ============== Burrow api
### create new burrow record
POST {{burrowApi}}
Content-Type: application/json

{
    "bookId" : "sadada",
    "BookName" : "sagar pyakurel",
    "thumbnail" : "http://....",
    "userId": "123456",
    "userName": "how to code",
    "returnDate": "2023-09-05"
}