

@rootApi = http://localhost:8000

@userApi = {{rootApi}}/api/v1/user

@burrowApi = {{rootApi}}/api/v1/burrow

@bookApi = {{rootApi}}/api/v1/book

@reviewApi = {{rootApi}}/api/v1/review


### Server Testing 
GET {{rootApi}}


# =========== user Api 

### Get User 
GET  {{userApi}}
Content-Type: application/json



### Create data in database
POST {{userApi}}
Content-Type: application/json

{
    "role": "admin",
    "fName": "Sagar",
    "lName": "Pyakurel",
    "phone" : "045235",
    "address" : "Sydney",
    "email" : "pwsedaasada@email",
    "password": "123456"
}



# ============= Book Api 
### get all the book 
GET {{bookApi}}
Authorization: 64fbf5dd6f5d061703eef179


# ============== Burrow api
### Get burrow request
GET {{burrowApi}}
Authorization: 64eaa3bd16003b72a4e2a870





### create new burrow record
POST {{burrowApi}}
Content-Type: application/json

{
    "bookId": "skjfo9844",
    "BookName": "prem acharya",
    "thumbnail": "http://...",
    "userId": "asljflj02840",
    "userName": "how to code",
    "returnDate": "2023-12-12"
}

# ============ review api 
### get reviews
GET {{reviewApi}}